# Generated by Django 2.0.7 on 2020-03-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='title1',
            field=models.TextField(default=''),
        ),
    ]
