# Generated by Django 2.0.7 on 2020-03-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200304_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title1',
            new_name='businessModel',
        ),
        migrations.AddField(
            model_name='article',
            name='competitors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='industries',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='marketOpportunity',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='poc',
            field=models.TextField(default=''),
        ),
    ]
