# Generated by Django 2.0.7 on 2020-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200304_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='demoLink',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='mainTech',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='painPoint',
            field=models.TextField(default=''),
        ),
    ]
